import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import AuthProvider from "./auth/auth.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme
          appearance="dark"
          accentColor="crimson"
          grayColor="sand"
          radius="large"
          scaling="95%"
        >
          <AuthProvider>{children}</AuthProvider>
        </Theme>
      </body>
    </html>
  );
}
